AF: Afrikaans
SQ: Albanian
AM: Amharic
ARA: Arabic
HY: Armenian
AS: Assamese
AY: Aymara
AZ: Azerbaijani
BM: Bambara
EU: Basque
BE: Belarusian
BN: Bengali
BHO: Bhojpuri
BS: Bosnian
BG: Bulgarian
CA: Catalan
CEB: Cebuano
NY: Chichewa
CHS: Chinese
ZH_HANT: Chinese (Traditional)
CO: Corsican
HRV: Croatian
CSY: Czech
DA: Danish
DV: Dhivehi
DOI: Dogri
NLD: Dutch
ENG: English
EO: Esperanto
ET: Estonian
EE: Ewe
TL: Filipino
FI: Finnish
FRA: French
FY: Frisian
GL: Galician
KA: Georgian
DEU: German
EL: Greek
GN: Guarani
GU: Gujarati
HT: Haitian Creole
HA: Hausa
HAW: Hawaiian
IW: Hebrew
HI: Hindi
HMN: Hmong
HUN: Hungarian
IS: Icelandic
IG: Igbo
ILO: Ilocano
IND: Indonesian
GA: Irish
ITA: Italian
JPN: Japanese
JW: Javanese
KN: Kannada
KK: Kazakh
KM: Khmer
RW: Kinyarwanda
GOM: Konkani
KOR: Korean
KRI: Krio
KU: Kurdish (Kurmanji)
CKB: Kurdish (Sorani)
KY: Kyrgyz
LO: Lao
LA: Latin
LV: Latvian
LN: Lingala
LT: Lithuanian
LG: Luganda
LB: Luxembourgish
MK: Macedonian
MAI: Maithili
MG: Malagasy
MS: Malay
ML: Malayalam
MT: Maltese
MI: Maori
MR: Marathi
MNI-MTEI: Meiteilon (Manipuri)
LUS: Mizo
MN: Mongolian
MY: Myanmar (Burmese)
NE: Nepali
NO: Norwegian
OR: Odia (Oriya)
OM: Oromo
PS: Pashto
FA: Persian
POL: Polish
PTB: Portuguese
PA: Punjabi
QU: Quechua
ROM: Romanian
RUS: Russian
SM: Samoan
SA: Sanskrit
GD: Scots Gaelic
NSO: Sepedi
SRP: Serbian
ST: Sesotho
SN: Shona
SD: Sindhi
SI: Sinhala
SK: Slovak
SL: Slovenian
SO: Somali
ESP: Spanish
SU: Sundanese
SW: Swahili
SV: Swedish
TG: Tajik
TA: Tamil
TT: Tatar
TE: Telugu
THA: Thai
TI: Tigrinya
TS: Tsonga
TRK: Turkish
TK: Turkmen
AK: Twi
UKR: Ukrainian
UR: Urdu
UG: Uyghur
UZ: Uzbek
VIN: Vietnamese
CY: Welsh
XH: Xhosa
YI: Yiddish
YO: Yoruba
ZU: Zulu
