# Cấu hình giới hạn khả năng của từng dịch giả.
# Do không phải AI nào cũng hỗ trợ tốt mọi ngôn ngữ.
TRANSLATOR_GROUPS:
  '--- OFFLINE MODELS (No API Key) ---':
  - sugoi
  - m2m100
  - m2m100_big
  - nllb
  - nllb_big
  - mbart50
  - jparacrawl
  - jparacrawl_big
  - qwen2
  - qwen2_big
  - offline
  '--- API-BASED (Requires Setup) ---':
  - gemini
  - deepseek
  - groq
  - openai
  - custom_openai
  '--- OTHER ACTIONS ---':
  - original
  - none
TRANSLATOR_CAPABILITIES:
  gemini:
    __any__: __all__
  deepseek:
    __any__: __all__
  groq:
    __any__: __all__
  openai:
    __any__: __all__
  custom_openai:
    __any__: __all__
  sugoi:
    JPN:
    - ENG
  jparacrawl:
    JPN:
    - ENG
  jparacrawl_big:
    JPN:
    - ENG
  nllb:
    __any__: __all__
  nllb_big:
    __any__: __all__
  m2m100:
    __any__: __all__
  m2m100_big:
    __any__: __all__
  mbart50:
    __any__: __all__
  qwen2:
    __any__: __all__
  qwen2_big:
    __any__: __all__
  offline:
    __any__: __all__
  original: {}
  none: {}
LOG_COLORS:
  ERROR: '#E74C3C'
  SUCCESS: '#2ECC71'
  PIPELINE: '#5DADE2'
  WARNING: '#F39C12'
  INFO: default
  DEBUG: gray
  RAW: gray
