"""
=============================================================================
INTEGRITY NOTES (For AI Agents):
- MODULE: app.core.desktop.config.studio_ui_map
- RESPONSIBILITY: studio_ui_map.py module logic.
- CALLED BY: Various
- CALLS TO: Various
- IN = OUT: Defines logic for app.core.desktop.config.studio_ui_map.
=============================================================================
"""
STUDIO_UI_MAP = \
{   'General & Translator': {   'processing_device': {   'widget': 'segmented_button'},
                                'target_lang': {   'widget': 'optionmenu_languages'},
                                'translator_category': {   'widget': 'segmented_button'},
                                'ai_mode': {'widget': 'segmented_button'},
                                'pool_name': {   'widget': 'pool_profile_selector',
                                                 'service': 'Translator'},
                                'api_name': {   'widget': 'api_profile_selector',
                                                'service': 'Translator'},
                                'offline_translator': {'widget': 'optionmenu'},
                                'ai_translator': {'widget': 'optionmenu'},
                                'ai_endpoint': {'widget': 'entry'},
                                'ai_model': {'widget': 'ai_model_selector'},
                                'enable_translator_chain': {   'widget': 'checkbox'},
                                'ai_key': {'widget': 'entry'},
                                'max_retries': {'widget': 'spinbox'},
                                'translator_chain': {   'widget': 'translator_chain_builder'},
                                'merge_nearby_boxes': {   'widget': 'checkbox',
                                                          'section': 'advanced'},
                                'no_text_lang_skip': {   'widget': 'checkbox',
                                                         'section': 'advanced'},
                                'max_request_length': {'widget': 'spinbox'},
                                'system_prompt_profile': {   'widget': 'optionmenu'},
                                'skip_lang': {   'widget': 'open_yaml_button',
                                                 'section': 'advanced'}},
    'Detector & OCR': {   'ocr_category': {'widget': 'segmented_button'},
                          'offline_detector': {'widget': 'optionmenu'},
                          'detection_size': {   'widget': 'spinbox',
                                                'recommendation': True},
                          'offline_ocr': {'widget': 'optionmenu'},
                          'ocr_ai_mode': {'widget': 'segmented_button'},
                          'ocr_pool_name': {   'widget': 'pool_profile_selector',
                                               'service': 'OCR'},
                          'ocr_api_name': {   'widget': 'api_profile_selector',
                                              'service': 'OCR'},
                          'api_ocr': {'widget': 'optionmenu'},
                          'ocr_api_endpoint': {'widget': 'entry'},
                          'ocr_api_model': {'widget': 'ai_model_selector'},
                          'ocr_api_key': {'widget': 'entry'},
                          'ignore_bubble': {   'widget': 'slider',
                                               'options': {   'number_of_steps': 50},
                                               'value_format': '{:.0f}'},
                          'text_threshold': {   'widget': 'slider',
                                                'value_multiplier': 0.01,
                                                'value_format': '{:.2f}',
                                                'section': 'advanced'},
                          'box_threshold': {   'widget': 'slider',
                                               'value_multiplier': 0.01,
                                               'value_format': '{:.2f}',
                                               'section': 'advanced'},
                          'unclip_ratio': {   'widget': 'slider',
                                              'value_multiplier': 0.1,
                                              'value_format': '{:.1f}',
                                              'section': 'advanced'},
                          'det_rotate': {   'widget': 'checkbox',
                                            'section': 'advanced'},
                          'det_auto_rotate': {   'widget': 'checkbox',
                                                 'section': 'advanced'},
                          'det_invert': {   'widget': 'checkbox',
                                            'section': 'advanced'},
                          'det_gamma_correct': {   'widget': 'slider',
                                                   'value_multiplier': 0.1,
                                                   'value_format': '{:.1f}',
                                                   'section': 'advanced'},
                          'min_text_length': {   'widget': 'slider',
                                                 'section': 'advanced',
                                                 'options': {   'number_of_steps': 10},
                                                 'value_format': '{:.0f}'},
                          'filter_text': {'widget': 'open_yaml_button'},
                          'prob': {'widget': 'entry', 'section': 'advanced'}},
    'Image & Inpainter': {   'inpainter': {'widget': 'optionmenu'},
                             'enable_advanced_diffusion': {   'widget': 'checkbox',
                                                              'section': 'advanced'},
                             'diffusion_model': {   'widget': 'optionmenu',
                                                    'section': 'advanced'},
                             'sd_base_model': {   'widget': 'optionmenu',
                                                  'section': 'advanced'},
                             'enable_upscaler': {'widget': 'checkbox'},
                             'upscaler': {'widget': 'optionmenu'},
                             'upscale_ratio': {'widget': 'optionmenu'},
                             'inpainting_precision': {'widget': 'optionmenu'},
                             'inpainting_size': {   'widget': 'spinbox',
                                                    'recommendation': True}},
    'Render & Output': {   'renderer': {'widget': 'optionmenu'},
                           'font_family': {'widget': 'combobox_fonts'},
                           'font_color': {'widget': 'entry_with_button'},
                           'outline_color': {'widget': 'entry_with_button'},
                           'outline_width': {   'widget': 'slider',
                                                'value_format': '{:.0f}'},
                           'is_bold': {'widget': 'checkbox'},
                           'alignment': {'widget': 'optionmenu'},
                           'font_size_offset': {   'widget': 'slider',
                                                   'value_format': '{:.0f}'},
                           'font_size': {   'widget': 'slider',
                                            'value_format': '{:.0f}',
                                            'section': 'advanced'},
                           'line_spacing': {   'widget': 'slider',
                                               'value_format': '{:.0f}',
                                               'section': 'advanced'},
                           'direction': {   'widget': 'optionmenu',
                                            'section': 'advanced'},
                           'disable_font_border': {   'widget': 'checkbox',
                                                      'section': 'advanced'},
                           'uppercase': {   'widget': 'checkbox',
                                            'section': 'advanced'},
                           'lowercase': {   'widget': 'checkbox',
                                            'section': 'advanced'},
                           'font_size_minimum': {   'widget': 'slider',
                                                    'options': {   'number_of_steps': 41},
                                                    'value_format': '{:.0f}',
                                                    'section': 'advanced'}},
    'Output & Export': {   'output_format': {'widget': 'optionmenu'},
                           'export_mode': {'widget': 'optionmenu'}},
    'Extra Settings': {   'memory_mode': {'widget': 'optionmenu'},
                          'context_window': {   'widget': 'spinbox',
                                                'options': {'step': 1}},
                          'stride_window': {   'widget': 'spinbox',
                                               'options': {'step': 1}},
                          'enable_double_check': {'widget': 'optionmenu'},
                          'api_key_manager': {'widget': 'api_key_manager'},
                          'app_language': {'widget': 'optionmenu'},
                          'enable_verbose_output': {   'widget': 'checkbox',
                                                       'tooltip_color': 'red'}}}
